{
    'name': "Vardhman Homepage",
    'version': '1.0',
    'summary': """Vardhman Homepage """,
    'description': """
    Vardhman Homepage
""",
    'category': 'Theme',
    'author': '',
    'depends': ['website','hr', 'website_blog', 'mass_mailing', 'website_event'],
    'data': [
        'security/ir.model.access.csv',
        'views/slider.xml',
        'views/hr_employee.xml',
        # 'views/portal_hr_applicant_templates.xml',
        # 'views/cportal_hr_applicant_templates.xml',
        'views/home_page_main_layout.xml',
        'views/employee_birthday.xml',
        'views/masters.xml',
        'views/employee_workanniversary.xml',
        'views/employee_marriageanniversary.xml',
        'views/useful_links.xml',
        'views/test.xml',
        'wizard/employee_birthday_wizard.xml',
        'wizard/employee_workanniversary_wizard.xml',
        'wizard/employee_marriageanniversary_wizard.xml',
        'wizard/create_from_master.xml',
    ],
    'demo': [],
    'images': [],
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
