{
    'name': "Vardhman Health Postal",
    'version': '1.0',
    'summary': """Vardhman Portal """,
    'description': """
    Vardhman Homepage
""",
    'category': 'Human Resources',
    'author': '',
    'depends': ['website','hr','board'],
    'data': [
        'security/ir.model.access.csv',
        'security/health_portal.xml',
        'security/accidents.xml',
        'security/fire_incident.xml',
        'security/audit.xml',
        'security/monthly_incident.xml',
        'security/zone_audit.xml',
        'security/best_practice.xml',
        'security/near_miss_info.xml',
        'security/safety_comm.xml',
        'security/safety_obs.xml',
        'security/unsafe_work.xml',
        'security/why_why_analysis.xml',
        'security/document_repository.xml',
        'views/masters.xml',
        'views/accidents.xml',
        'views/fire_incident.xml',
        'views/audit.xml',
        'views/monthly_incident.xml',
        'views/zone_audit.xml',
        'views/best_practice.xml',
        'views/near_miss_info.xml',
        'views/safety_comm.xml',
        'views/safety_obs.xml',
        'views/unsafe_work.xml',
        'views/why_why_analysis.xml',
        'views/document_repository.xml',
        'views/board_views.xml',
    ],
    'demo': [],
    'images': [],
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
